"""V1.1 SP11: Zentraler Changelog fuer die Versionsinfo-Seite.

Eintraege absteigend nach Version sortiert. Neue Releases hier anhaengen.
Format pro Eintrag: (display_name, datum_iso, lines).
"""

CHANGELOG: list[tuple[str, str, list[str]]] = [
    ("V2.1 SP1", "2026-06-25", [
        "Vier neue eigenstaendige Apps rund um die gemeinsame NMGone-Datenbank: 'Wareneingang & Retouren' (GDP-Chargenrueckverfolgung, Kundenqualifizierung, Retouren mit Gutschrift), 'Meldungen' (GDP-Meldewesen, Kuehlsachenkontrolle, Selbstinspektion), 'Einkauf' (Beschaffung EU-Ausland, §129-Margenrechner, Aufgaben/Meldungen) und 'Parameter' (Berechtigungen: wer darf was - Rollen, Overrides, Admin-PIN).",
        "Demo-Modus: liegt nur eine Demo-Datenbank vor, startet das Programm automatisch im Demo-Betrieb und ist ueberall sichtbar als 'NMGone Demo' / [DEMO] markiert - Demo- und Echtbetrieb sind nicht mehr verwechselbar.",
        "Kunden: Offline-Deutschlandkarte (ohne Internetzugang) fuer die Kundenuebersicht.",
        "Kasse, Mitarbeiter & Personal, Hilfe und Dashboard ueberarbeitet und erweitert; neue Datenbank-Migrationen fuer die neuen Apps.",
        "Neue Start-Verknuepfungen (.bat) fuer Wareneingang, Meldungen und Parameter.",
    ]),
    ("V2.1.0", "2026-06-24", [
        "Neuer Meilenstein V2.1.0 - fasst den kompletten V2.0-Zyklus (V2.0 inkl. SP1-SP4: Bedarfsanalyse, Mitarbeiter & Personal, Kasse, Faktura, Report, neues Theme) zu einer stabilen Gesamtversion zusammen.",
        "Faktura ist jetzt direkt aus NMGone startbar - eigene Kachel auf der Apps-Seite und im Dashboard-Schnellzugriff (eigenes Fenster/Taskleisten-Icon).",
        "Hilfe: das bebilderte Handbuch ist vollstaendig - echte Screenshots fuer alle Module sowie neue Kapitel zu Faktura und Mitarbeiter & Personal.",
        "Hilfe-Kasse erweitert: EK/Lagerwert, Freie Position, Vorbestellungen, MSK & Lieferschein und Auftrags-Verlauf Schritt fuer Schritt erklaert.",
        "Anpassbare Druckvorlagen: Lieferschein (vorlagen/lieferschein.html) und Defektmeldung (vorlagen/defektmeldung.html) mit eigenen Firmendaten/Logo gestaltbar.",
    ]),
    ("V2.0 SP4", "2026-06-24", [
        "Neue eigenstaendige App 'Faktura' - rechtskonforme Rechnungen und Gutschriften (Deutschland), eigenes Fenster/Taskleisten-Icon, teilt sich die Datenbank mit NMGone und der Kasse.",
        "Rechtssicher: der APU wird je Position zum Beleg eingefroren (spaetere Preislisten aendern alte Belege nicht); festgeschriebene Belege sind unveraenderbar (GoBD), Korrektur nur per Storno; lueckenlose Belegnummern je Belegart.",
        "Auftraege: zeigt je Apotheke die offenen (noch nicht abgerechneten) Verkaeufe aus der Kasse (Auftraege, Artikel, Umsatz, Umsatz nach Rabatt) mit Zeitraum-Filter; daraus per Klick eine Sammelrechnung erstellen (Rechnungsdatum waehlbar), Kunden 'fuer jetzt' ausblenden.",
        "Storno einer Rechnung erzeugt eine Storno-Rechnung mit negativen Betraegen und gibt die zugehoerigen Auftraege wieder frei (tauchen erneut in der Liste auf, in der Kasse weiter bearbeitbar).",
        "Gutschriften: manuell zur Rechnung ODER automatisch beim Festschreiben - wahlweise % vom Netto/Brutto, Fixbetrag oder 'Auftragsrabatt' (Rechnung zum vollen APU, Gutschrift bildet je Artikel den Rabatt ab, z.B. 60%); §17-USt-Korrektur. Beim Stornieren der Rechnung werden zugehoerige Gutschriften optional mit storniert.",
        "Quartalsverguetung: feste Euro-Verguetung je Kunde ab konfigurierbarer Umsatzschwelle (Staffel), berechnet aus den festgeschriebenen Rechnungen eines Quartals (stornierte zaehlen nicht).",
        "Einstellungen mit aufklappbarem Menue: Firmendaten (inkl. automatischer Gutschrift), frei konfigurierbare Belegnummern (Platzhalter wie RE-{JJJJ}-{NR:5}) und Layouts.",
        "Belegvorlage frei gestaltbar (gilt fuer Rechnung, Gutschrift, Quartalsverguetung): Akzentfarbe, Spalten, Titel/Kopftext je Belegart, Fusstext, Vorschau-PDF - plus Drag-&-Drop-Layout-Editor mit eigenen Feldern (Freitext und Datenfelder).",
        "Ablage als PDF im Ordnerschema (Rechnungen/Jahr/Monat, Gutschriften/Jahr/Monat, Quartalsverguetung/Jahr/Quartal; Dateiname Kundennummer;Belegnummer;Apotheke;Datum); Ordner direkt aus dem Programm zu oeffnen. Spaeter auf SharePoint/OneDrive umlenkbar.",
        "Summen auf der Rechnung als Kennzahl-Karten (wie im Kasse-Tagesabschluss).",
    ]),
    ("V2.0 SP3", "2026-06-24", [
        "Kasse: Lieferschein - wird beim Setzen von 'In MSK erfasst' angeboten und ist jederzeit in der Verkaufs-Detailansicht erneut erzeugbar (Charge/Verfall, ohne Preise). Beim manuellen Erzeugen wird gefragt, ob der Auftrag in MSK erfasst wurde.",
        "Kasse-Verkauf: reicht der Bestand nicht, kann die verfuegbare Menge sofort als Bestellung geliefert und der Rest als Vorbestellung aufgenommen werden (oder nur der vorhandene Bestand abverkauft werden).",
        "Kasse-Verkauf: 'Freie Position' - frei benannter Posten mit eigenem Preis/Menge/Rabatt, nicht bestandsgefuehrt, wird gespeichert und erscheint mit Preis auf der Auftragsbestaetigung.",
        "Kasse: neuer Reiter 'Auswertung' - Umsatz je Tag/Monat/Jahr (Anzahl Verkaeufe, Anzahl Packungen, APU Brutto, Rabatt (Netto), APU Netto), Verfall (Zeitraum 3/6/9/12 Monate oder Alle; abgelaufen rot, bald gelb) und Inventur. Kennzahlen als Karten, Reiter im NMGone-Blau.",
        "Kasse-Tagesabschluss: eigener Reiter mit Kalender-Datumsauswahl, fortlaufender Nummer und Kennzahlen (Verkaeufe, Packungen, APU-, Rabatt-, Umsatz-Summe). Wird jeden Abend automatisch (Uhrzeit einstellbar, Standard 18 Uhr) erzeugt und nummeriert; verpasste Vortage werden beim Start nachgeholt.",
        "Kasse: EK (Einkaufspreis) im Wareneingang erfassbar (mit APU vorbelegt) und beim Import uebernommen; daraus ueberall der Lagerwert (EK x Bestand) zusaetzlich zum Verkaufswert (APU x Bestand) - Lagerbestand, Artikel, Verfall, Inventur (inkl. PDF).",
        "Kasse-Artikel: Summenleiste mit Gesamtbestand, Verkaufswert und Lagerwert; passt sich der Suche an. Kasse startet maximiert (Vollbild).",
        "Kasse: neuer Reiter 'Defektmeldung' - Nichtverfuegbarkeits-Bescheinigung fuer die Apotheke (Apotheke + Artikel waehlen, Grund angeben).",
        "Kasse: Auftrags-Verlauf (wer/was/wann) je Auftrag einsehbar und als PDF; Aenderungs-Protokoll gefiltert als PDF exportierbar.",
        "Kasse: neuer Reiter 'Einstellungen' - Firmendaten (Dokumentkopf), Defektmeldung-Rechtstext und Tagesabschluss-Uhrzeit direkt in der App pflegbar.",
        "Kasse: robusterer Datenbankzugriff (busy_timeout) fuer den Parallelbetrieb von NMGone und Kasse.",
    ]),
    ("V2.0 SP2", "2026-06-24", [
        "Bedarfsanalyse: liest jetzt auch alte bzw. als .xls gespeicherte XML-/HTML-Tabellen (typische Apotheken-/Grosshandels-Exporte) sowie CSV/TXT; robustere Spaltenerkennung (z.B. 'Packungen' wird als Absatzmenge erkannt).",
        "Bedarfsanalyse: kommt eine PZN mehrfach vor (Verkaufslisten), koennen auf Nachfrage die Mengen je PZN summiert werden - Retouren (negative Mengen) werden dabei verrechnet.",
        "Kurzbericht zur Bedarfsanalyse als Excel UND PDF mit Diagrammen: Einsparpotenzial auf 6 und 12 Monate hochgerechnet, Top-10-Hebel-Artikel und Kennzahlen; Fokus auf Hochpreiser (nur Taxe-EK ueber 200 Euro).",
        "Neues Tabellenblatt 'Wirkstoff & NMG-Austausch': je abgegebenem Artikel der Wirkstoff und die passenden NMG-Artikel - eine Zeile je NMG-Artikel und damit als Pivot-Grundlage nutzbar.",
        "Wirkstoff-Abgleich: gibt es keine direkte NMG-Zuordnung, wird ueber den Wirkstoff eine NMG-Empfehlung gesucht und farblich markiert (gruen = eindeutig, gelb = mehrere Optionen). 'Austauschbar gegen' bleibt leer, wenn bereits eine NMG-PZN gefunden wurde.",
        "Gelbe Liste (Biosimilars): neuer Import-Knopf unter 'Daten aktualisieren'.",
        "Stabilitaet: die Oberflaeche friert nach einer Auswertung nicht mehr ein (die Nachbearbeitung laeuft im Hintergrund); nicht lesbare Dateien melden sich jetzt klar, statt scheinbar haengen zu bleiben.",
        "Schulbank-Korrektur: beim Ablehnen von 'Uebernommen'-Eintraegen werden nur noch die markierten Eintraege deaktiviert (vorher konnten ueber kollidierende IDs versehentlich andere Eintraege getroffen werden).",
    ]),
    ("V2.0 SP1", "2026-06-24", [
        "Neue eigenstaendige App 'Mitarbeiter & Personal' - oeffnet sich ueber die Mitarbeiter-Kachel in einem eigenen Fenster und teilt sich die Datenbank mit NMGone.",
        "Organigramm: Mitarbeiter als verschiebbare Karten, per Linie verbinden und wieder loesen; Beziehungsart (disziplinarisch/fachlich/Vertretung) farblich unterschieden, die primaere Beziehung bildet den Baum; Auto-Layout und Filter nach Teilbereich/Abteilung.",
        "Abwesenheiten/Urlaub: Team-Kalender in Monats- oder Jahresansicht, Eintragen ueber Kalender-Datumsauswahl; Arten Urlaub, Sonderurlaub (mit Grund), Krankheit, Fortbildung und Sonstiges.",
        "Urlaubskonto: Urlaubsanspruch je Mitarbeiter, Resturlaub-Berechnung (nur Werktage) und gesetzlicher Hinweis auf den 31.03.-Verfall; ein offener Resturlaub kann der personalverantwortlichen Person zur Entscheidung (verfallen lassen ja/nein) gemeldet werden.",
        "Arbeitsbereiche: je Mitarbeiter alle Aufgabengebiete nach Kategorien gruppiert; Vertretungsketten (Verantwortlich -> 1./2./3. Vertretung) wahlweise je Mitarbeiter oder je Bereich dargestellt.",
        "Einstellungen (Zahnrad): Kategorien der Arbeitsbereiche frei anlegen, umbenennen (zieht alle zugeordneten Bereiche mit) und loeschen.",
        "Neue Mitarbeiterkarte: die Daten des angemeldeten Benutzers werden vorbelegt.",
    ]),
    ("V2.0", "2026-06-23", [
        "Neuer Meilenstein V2.0 - buendelt mehrere neue Programme unter dem bekannten NMGone-Dach.",
        "Bedarfsanalyse (ehem. 'Neue Auswertung') mit separatem Kurzbericht: Excel + PDF inkl. Diagrammen fuer die schnelle Uebersicht.",
        "Mitarbeiter: frei definierbare Custom-Felder (EAV) sowie Vorgesetzten-/Zustaendigkeits-Matrix als Grundlage fuer das Organigramm.",
        "Hilfe: bebildertes Handbuch direkt im Programm aufrufbar.",
        "Report-Programm: modeluebergreifende Auswertung saemtlicher NMGone-Logs an einer Stelle.",
        "Einheitliches Design ueber alle Module (zentrales Theme, dunkle Seitenleiste).",
        "Biosimilar-Wissensbasis (Gelbe Liste) als Grundlage fuer kuenftige Wirkstoff-Zuordnung.",
    ]),
    ("V1.2 SP2", "2026-06-22", [
        "Kasse: grafischer Umbau - moderne Oberflaeche im NMGone-Blau. Navigationsleiste mit aktivem Akzent-Balken und Hover-Effekt, Kopfzeile mit Untertitel je Ansicht, Inhalte in klaren Karten statt der alten Rahmen.",
        "Kasse: alle Tabellen einheitlich gestylt (hoehere Zeilen, hervorgehobener Spaltenkopf, blaues Auswahl-Highlight). Reine Optik - Bedienung und Daten unveraendert.",
        "Kunden App heisst wieder 'Kunden'. Kundenmaske neu als kompaktes Reiter-Fenster (Stammdaten, Artikel-Rabatte, Analysen, Verkaufte Artikel, Notizen) statt Vollbild; Typ PK/ZW als Pflicht-Auswahl, Quartalsverguetung als Ja/Nein.",
        "Kunden App: Formular ausgebaut - MSK-Kundennummer (auto), Inhaber (Titel/Anrede/Vor-/Zuname), Verantwortlicher Besteller, Rechnungs-E-Mail/-Art, Hausnummer. PLZ-Pruefung mit Ort-Autofill offline (10.814 PLZ).",
        "Kunden App: spezielle Artikel-Rabatte je Kunde pflegbar - sie wirken direkt in der Kasse (PK-Kondition vor NMG-Rabatt).",
        "Anzeige 'ZF' -> 'ZW' umbenannt (nur Beschriftung in UI, Filtern, Produktanalyse-Sheets/Dateinamen; intern bleibt alles unveraendert).",
    ]),
    ("V1.2 SP1", "2026-06-22", [
        "Vorbestellungen: neues Sammelfenster 'Mehrere in Verkauf uebernehmen' - alle offenen Vorbestellungen mit Menge und aktuellem Bestand, Uebernehmen-Menge je Zeile anpassbar (0 = ueberspringen), Uebernahme in einem Rutsch (ein Kunde gleichzeitig).",
        "Verkaeufe + Verkauf: Suche und Anzeige nach Auftrag-Nr (neue Auftrag-Spalte in der Liste). Im Verkauf nur Ansicht - es wird kein neuer Auftrag angelegt.",
        "Verkaeufe-Detail zeigt nur noch echte Bestellungen (Vorbestellungen gehoeren in den Vorbestellungen-Reiter); 'Pos.'-Zaehler und Gesamt-Netto rechnen nur Bestellungen.",
        "Kunde: 'Gekaufte Artikel' zeigt jetzt ALLE vom Kunden gekauften Artikel mit waehlbarem Zeitraum (3 / 6 / 12 Monate oder freie Eingabe) statt nur Top-10/12 Monate.",
        "Wareneingang: EK wird nicht mehr abgefragt - er entspricht immer dem APU aus den Stammdaten. Verfalldatum darf jetzt auch ohne Trenner eingegeben werden (1226 -> 12/26, 122026 -> 12/2026).",
        "Kasse startet aus NMGone als eigenes Programm mit getrenntem Taskleisten-Icon (eigene App-ID NMG.Kasse); NMGone und Kasse sind dadurch getrennte Taskleisten-Gruppen.",
        "Umbenennung 'Kunden-Center' -> 'Kunden App' (Kacheln, Titel, Dialoge).",
    ]),
    ("V1.2.0", "2026-06-22", [
        "Neuer Meilenstein mit der NMG Kassen-App - als eigenes Programm und eigene Verknuepfung; eine NMGone-Installation bringt die Kasse mit (NMGone.exe --kasse).",
        "Kasse: Verkauf an Apotheken (globale Kunden-/Artikelsuche, Charge/Verfall aus Lager, Rabatt-Kaskade PK->NMG->manuell, Liefertermin-Automatik).",
        "Wareneingang -> Lagerbestand (Charge/Verfall), Datei-Import (TXT/CSV/Excel) fuer Kunden, Wareneingang und Historie (Verkaeufe/Vorbestellungen).",
        "Vorbestellungen: Disposition, Teil-Uebernahme in den Verkauf, abgesagt-Auswertung. Verkaeufe: Filter (Status/Zeitraum/MSK), Storno mit Bestand-Rueckbuchung, Top-10-Artikel pro Kunde.",
        "MSK-Erfassungsstatus pro Verkauf (offen/erfasst, wer/wann) + Schnellmarkierung. Auftragsbestaetigung (Druck/E-Mail) jederzeit erneut erzeugbar.",
        "Aenderungs-Protokoll (wer/was/wann) mit Volltext- und Aktion-Filter. Manuelle Bestandskorrektur erfordert jetzt einen Pflicht-Kommentar (Grund) - protokolliert und auswertbar.",
        "Alle Tabellen per Spaltenkopf sortierbar; einheitlicher NMGone-Flat-Button-Stil.",
    ]),
    ("V1.1 SP19", "2026-06-19", [
        "Neue Auswertung ist 11x schneller: trace_lookup_source nutzt Index-Cache statt pro Zeile die komplette Austauschdatenbank zu scannen. 414 Zeilen jetzt in ~16 s statt ~3 Min.",
        "Bugfix Neue Auswertung (SP18-Regression): Doppelklick-Schutz auf 'Auswertung starten' verhindert stille Mehrfachstarts (Log zeigte 90 Aufrufe in einer Sekunde).",
        "Bugfix Status-Box: erscheint jetzt zuverlaessig auch wenn die rechte Sidebar eingeklappt ist (Fallback am Hauptfenster oben rechts).",
        "Bugfix Background-Jobs: Exceptions in on_done/on_error werden ins Fehler-Log geschrieben + messagebox angezeigt statt geraeuschlos zu verschwinden.",
        "NMG-Rabatte-Uebersicht (neue Kachel in Apps + Dashboard): 4 Reiter - alle Rabatte mit Filter, Statistik, Diff zum letzten Stand, Verlauf pro PZN.",
        "Vor jedem PK-Rabatte-Import wird automatisch ein Snapshot des aktuellen Stands angelegt - damit Diff/Verlauf nachvollziehbar sind.",
        "Auto-Restart nach Setup: NMGone startet nach jedem Update automatisch wieder (kein Haekchen mehr am Wizard-Ende noetig).",
    ]),
    ("V1.1 SP18", "2026-06-19", [
        "Neue Auswertung laeuft jetzt im Hintergrund (analog manueller Import in SP15). UI bleibt klickbar.",
        "Background-Status-Box umgezogen: von rechts oben im Header in die rechte Sidebar ueber den Backup-Status.",
        "Wenn keine Jobs laufen, ist die Box unsichtbar.",
        "UnknownInputFormatError + Format-Assistent-Pfad jetzt in on_error des Background-Jobs (interaktiv im UI-Thread).",
    ]),
    ("V1.1 SP17", "2026-06-19", [
        "Manueller Import: nicht-erkannte Dateien werden uebersprungen statt pro-Datei modal abgefragt.",
        "TXT-Sammeldatei 'nicht_erkannte_dateien_TIMESTAMP.txt' in importierte_analysen/<typ>/<Jahr>/Q<n>/ mit Liste der Dateinamen + Fehlertext.",
        "Am Ende EINE einmalige Sammel-Frage 'Sollen die N nicht-erkannten Dateien manuell gemapped werden?' (statt Pro-Datei-Dialog).",
        "Aufraeum: doppelte Statistik-Messagebox am Import-Ende war drin, jetzt nur noch einmal.",
    ]),
    ("V1.1 SP16", "2026-06-19", [
        "Import-Performance fuer rohdaten-Modus (Excel ohne Standard-Header).",
        "Vorher: pro Zeile mehrere SQL-Queries mit pzn_norm()-UDF in WHERE - Full-Table-Scan ueber zigtausend Eintraege.",
        "Jetzt: Pre-Cache vor der Schleife. Alle PZNs einmal sammeln, dann Basisdaten/Austausch/NMG-Stamm/Rabatte/Lieferfaehigkeit in einem Rutsch laden (IN-Lookup mit Index).",
        "Erwartet: 50-200x schneller im rohdaten-Modus. Bei erkanntem Header weiterhin der bereits schnelle Pfad aus SP13.",
    ]),
    ("V1.1 SP15", "2026-06-19", [
        "Manuelle Imports laufen jetzt im HINTERGRUND - kein blockierender Modal-Dialog mehr.",
        "Status-Box oben rechts mit Titel + aktueller Datei + Fortschritts-Balken; verschwindet nach Abschluss.",
        "UI bleibt waehrend des Imports klickbar; mehrere Imports koennen parallel laufen.",
        "Statistik-Toast unten in der Statusleiste nach Abschluss (8 s).",
        "Neue Methode _run_background analog _run_busy, aber non-modal.",
    ]),
    ("V1.1 SP14", "2026-06-19", [
        "Manuelle Imports: Fortschritts-Anzeige im Busy-Dialog. Zeigt 'Datei 5 von 96: foo.xlsx' statt 'Bitte warten'.",
        "Neuer _run_busy(..., progress=True)-Modus: Worker bekommt ein progress(text)-Callable und kann den Subtitle waehrend der Verarbeitung aktualisieren.",
    ]),
    ("V1.1 SP13", "2026-06-19", [
        "Manueller Analysen Import deutlich schneller: pro Excel-Zeile war vorher 2-3 Einzel-Queries als implizite Transaktion. Bei 5000 Zeilen = 10.000-15.000 Transaktionen, dauerte minutenlang.",
        "Fix: Inserts werden gesammelt und als executemany in einer Transaktion geschrieben; Duplikat-Check liest bestehende Schluessel einmal als Set.",
        "Erwartet: 5000 Zeilen jetzt in unter 30 s (vorher mehrere Minuten).",
        "Stellen: _insert_learning_suggestions, _insert_learning_suggestions_from_auswertung, import_historical_market_file (Positionen-INSERT).",
    ]),
    ("V1.1 SP12", "2026-06-19", [
        "Gespeicherte Analysen: Refresh nach Admin-Loeschen funktioniert wieder.",
        "Gespeicherte Analysen: 'Item end not found'-Fehler bei Seitenwechsel weg (defensive Guards).",
        "Manuelle Analysen Import: Fortschritts-Dialog (Busy-Modal) statt eingefrorenes UI.",
        "Manuelle Imports: Original-Datei wird in importierte_analysen/<PK|ZF>/<Jahr>/Q<n>/ kopiert.",
        "Kalender-Popup schliesst beim Klick ausserhalb.",
        "Dashboard-Editor: Fenster groesser, Speicher-Button immer sichtbar.",
        "Dashboard: 'Alles abwaehlen' funktioniert jetzt wirklich (Sentinel _NONE_ vs _EMPTY_).",
        "Globale Suche auf Startseite: Tabelle nur sichtbar wenn Treffer da; Hoehe nur 3 Zeilen.",
        "Produktanalyse: nur Artikel mit Namen im Artikelstamm.",
        "Re-Import: 'schon importiert' greift nur, wenn die Auswertung noch lebt.",
        "Neue Ordner-Struktur: ausgaben/<Kategorie>/<Jahr>/Q<n>/ und importierte_analysen/<PK|ZF>/<Jahr>/Q<n>/.",
    ]),
    ("V1.1 SP11", "2026-06-19", [
        "Produktanalyse: Basis-Info-Zeile und Beschreibungs-Zeile in den Excel-Sheets entfernt (Zeile 2 + 3).",
        "Versionsinfo: neue Seite mit Liste aller Versionen und Changelog pro Version.",
        "Startseite: 'Datenbankstatus'-Box (Werte waren nicht real) und Datenbank-Dateiname in 'Aktiver Bearbeiter' entfernt.",
        "Dashboard-Editor: 'Alles abwaehlen + Speichern' funktioniert jetzt (vorher Block-Dialog).",
        "Button-Style auf Hauptseiten und Sidebars vereinheitlicht.",
    ]),
    ("V1.1 SP10", "2026-06-19", [
        "Bug: Produktanalyse zeigt nur noch Artikel, die im Artikelstamm einen Namen haben (keine leeren Zeilen).",
        "Bug: Re-Import einer Datei klappt, wenn die zugehoerige Auswertung zwischendurch geloescht wurde.",
        "Gespeicherte Analysen: neue Filter-Buttons Importiert / Programm / Produktanalyse.",
        "Sidebar-Button 'Zeitraum LOESCHEN' (rot, Admin-Passwort, voller DB-Backup vorher).",
        "Datums-Felder als Kalender-Picker (tkcalendar) in Suche und Zeitraum-Dialogen.",
    ]),
    ("V1.1 SP9", "2026-06-19", [
        "Globale Suche: zeigt initial 3 Treffer + 'Mehr anzeigen (N)'-Button.",
        "Globale Suche als eigenes Toplevel-Tool (analog Vergleichs-Suche).",
        "Kachel in der Apps-Seite + Dashboard-Editor-Eintrag.",
    ]),
    ("V1.1 SP8", "2026-06-19", [
        "Gespeicherte Analysen: getrennte Suchfelder (Apotheke, Kunden-Nr., Kunde, Datum von/bis).",
        "'Auswertung oeffnen' oeffnet jetzt direkt die Excel.",
        "Zeitraum-Archivierung: Auswertungen wandern als ZIP nach backups/analysen_archiv/, DB-Zeilen werden geloescht.",
        "Archiv-Verwaltung: Liste der ZIPs, Doppelklick extrahiert Excel und oeffnet. Loeschen nur per Admin-Passwort.",
    ]),
    ("V1.1 SP7", "2026-06-19", [
        "Startseite: alte Austauschsuche entfernt, durch globale Suche ersetzt.",
        "Globale Suche findet Kunden, gespeicherte Analysen und Artikel parallel.",
        "Doppelklick verzweigt zu Kunden-Center, Excel oder Vergleichs-Suche.",
    ]),
    ("V1.1 SP6", "2026-06-19", [
        "Produktanalyse: zwei neue Reiter pro Kundentyp - 'NMG-Sortiment' und 'Austausch vorhanden'.",
        "Bei PK+ZF: 9 Reiter total (3 Sichten x 3 Reiter).",
    ]),
    ("V1.1 SP5", "2026-06-19", [
        "Vergleichs-Suche: Hersteller-Filter mit Wert (#hexal, #ratio, ...).",
        "Internes SQL-LIMIT bei Filtern auf 2000 hochgesetzt, damit Filter nicht ins Leere greifen.",
        "Aufraeumen: abstraktes #herst aus SP4 entfernt.",
    ]),
    ("V1.1 SP4", "2026-06-19", [
        "Vergleichs-Suche: Filter-Syntax mit '#' eingefuehrt: #nmg, #austausch, #schulbank, #wirkstoff, #herst.",
        "Unbekannte #-Tags werden verworfen, UND-Logik bei mehreren Filtern.",
    ]),
    ("V1.1 SP3", "2026-06-19", [
        "Vergleichs-Suche: 'Quelle'-Spalte im Austauschartikel-Detail-Panel.",
        "Datenbankuebersicht: 'Datenbankinhalte leeren' direkt erreichbar (Ctrl+Alt+A-Toggle entfaellt).",
    ]),
    ("V1.1 SP2", "2026-06-19", [
        "Neue Wirkstoff/Staerke-Datenbank (tbl_wirkstoff_staerke).",
        "Import-Button in Datenbankuebersicht. 162k Zeilen in ~14 s importiert.",
        "Vergleichs-Suche kann nach Wirkstoff, Hersteller und Staerke suchen.",
        "Detail-Panel zeigt Wirkstoff + Staerke.",
    ]),
    ("V1.1 SP1", "2026-06-18", [
        "Produktanalyse-Performance: UDFs in JOIN-/EXISTS-Klauseln entfernt.",
        "Direkter =-Join nutzt die vorhandenen PZN-Indizes, PK+ZF in ~183 ms statt >3 Minuten.",
    ]),
    ("V1.1.0", "2026-06-18", [
        "Meilenstein-Release. Neue Vergleichs-Suche als eigenes Toplevel-Fenster.",
        "Live-Suche nach PZN oder Artikelname ab 3 Zeichen.",
        "Sucht parallel in Austauschdatenbank, NMG-Stamm, Artikelstamm, PZN-Basisdaten.",
        "Detail-Panel zeigt Stammdaten + Austauschartikel-Tabelle.",
        "Dashboard-Editor um 20 % verkleinert, nicht mehr maximiert.",
    ]),
    ("V1.0 SP30", "2026-06-18", [
        "Produktanalyse mit Vorkommen + Erste/Letzte Sichtung + PZN-Normalisierung in Austausch-Filtern.",
    ]),
    ("V1.0 SP29", "2026-06-18", [
        "PK-Rabatte: PZN-Suffix '/N' (SK-Lagervariante) wird korrekt abgeschnitten.",
        "Max-Rabatt pro PZN, Counter-Refresh, Lieferfaehigkeit-Anzeige entfernt.",
    ]),
    ("V1.0 SP28", "2026-06-18", [
        "Rabatt-Parser-Fix beim PK-Import. Counter zeigen ehrliche Werte.",
    ]),
    ("V1.0 SP24-SP27", "2026-06-17", [
        "pzn_norm()-Lookup, Statusliste + Start-Warnung, In-Memory-Caches fuer Lookups.",
    ]),
]


def get_changelog() -> list[tuple[str, str, list[str]]]:
    """Liefert alle Changelog-Eintraege (neueste zuerst)."""
    return list(CHANGELOG)
